import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/navigation/page";
import Footer from "./components/fotter/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex-col justify-between max-w-[1320px] h-auto mx-auto my-0">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}